In [1]:
import numpy as np

from calculus import Array, Function

In [35]:
two = Array([[1, 2], [3, 4], [5, 6]])
two.shape

(3, 2)

In [37]:
print([list(row) for row in zip(*two)])
print(np.array(two).T)

[[1, 3, 5], [2, 4, 6]]
[[1 3 5]
 [2 4 6]]


In [40]:
three = Array([[[1, 2], [3, 4]], 
               [[5, 6], [7, 9]],
               [[10, 11], [12, 13]]])
three.shape

(3, 2, 2)

In [41]:
print(np.array(three).T)

[[[ 1  5 10]
  [ 3  7 12]]

 [[ 2  6 11]
  [ 4  9 13]]]


In [66]:
np.array([[list(row2) for row2 in zip(*row)] for row in zip(*three)])

array([[[ 1,  5, 10],
        [ 2,  6, 11]],

       [[ 3,  7, 12],
        [ 4,  9, 13]]])

In [ ]:
[[list(row2) for row2 in zip(*row)] for row in zip(*three)]

In [70]:
a = [1, 2, 3]

In [73]:
np.abs(a)

array([1, 2, 3])

In [74]:
Array([[1, -2, 3], [4, 5, -6]])[0, 1]

-2

In [75]:
np.array(Array([[1, -2, 3], [4, 5, -6]]))

array([[ 1, -2,  3],
       [ 4,  5, -6]])

In [76]:
Array([1, 2, 3]) +  Array([1, 2, 3])

[2, 4, 6]

In [2]:
import operator

In [3]:
operator.add(Array([1, 2, 3]), Array([1, 2, 3]))

[2, 4, 6]